### ISSUE TITLE
Great piece!

### ISSUE THREAD

**Issue by StarpTech** [lukeed/rosetta#1]
Hi, thanks for the lib. I test it in my app and it does a good job. The only thing I'm missing is a tiny lib for language detection (header on server-side + navigator.language on client-side). Based on the right user locale rosetta should use `en-US` or fallback to `en`.

**Comment by StarpTech** [comment]
Out of scope.

**Comment by lukeed** [comment]
Hey sorry! I dunno how/why I didn't get a notification for this 🤔 

While it's true this is out of scope (`rosetta` is the core functionality only; you pass in your dictionaries and decide how/when to use them since that's the easy part), I'll answer anyway since it's an important step.

***Client-side***

You have [`navigator.language`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) and [`navigator.languages`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) to work with. What those values will contain is totally dependent on your user's settings. 

The `language` (singular) is always the first value of the `languages` array, so I'll just use the array for this example:

```js
// Your App language targets (can use regionalities too)
const mylangs = ['en', 'es', 'pt'];

// Strip down to language code only (app specific)
const needle = str => mylangs.includes(str.split('-')[0]);

// Which language to use?
const lang = navigator.languages.find(needle) || '~default~';

// update rosetta
rosetta.locale(lang);
```

***Server-side***

You'll want to use the [`Accept-Language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) HTTP header. Every browser will send this by default. Any other HTTP client will (likely) need to send it manually.

Much like client-side, you just parse the value(s) given and determine if any of those match something you support. Otherwise, you'll revert to a default of your choice.

```js
// Same as before...
const mylangs = ['en', 'es', 'pt'];

// CHANGE: Split by RegExp (works client-side too)
const needle = str => mylangs.includes(str.split(/[-;]/g)[0]);

// (native 'http' API)
const header = res.getHeader('Accept-Language') || '';
//=> example: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7

const lang = header.split(',').find(needle) || '~default~';

// update rosetta
rosetta.locale(lang);
```

Hope that helps! 
Sorry again about the delay – I really don't know how that happened.

**Comment by StarpTech** [comment]
Hi @lukeed,
I solved it in exact this way :+1: thanks for your help.

**Comment by lukeed** [comment]
Nice :) No problem
