### ISSUE TITLE
Feature to skip the dot notation

### ISSUE THREAD

**Issue by mfbx9da4** [lukeed/rosetta#13]
My keys are stored like so

```
{
    "account.email.title": "Email",
    "account.familyName.title": "Last name",
    "account.givenName.title": "First name",
    "account.pushNotifications": "Enable push notifications",
    "account.removeFromDevice.logout": "Logout",
```

Would love to use this lib but can't without an option to skip dot notation. Could that be on the horizon?

**Comment by lukeed** [comment]
You can use array notation, which is slightly more annoying, but it will leave each segment as is.

Rosetta uses `dlv` directly for access, and so inherits its usage/conditions.

```js
i18n.t(['account.email.title']);
```

Had a project like this in the past, and eventually everyone agreed to use `:` instead of `.` within the dictionary keys

**Comment by mfbx9da4** [comment]
thanks
