### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by janhesters** [lukeed/rosetta#6]
Does Rosetta detect and set the default language automatically, or do we have to do that manually using the browser?

**Comment by lukeed** [comment]
Sorry! Somehow I unwatched the repository. TBH I think my phone lockscreen has been acting up in my pocket...

Rosetta just manages the dictionaries. Since this can be used anywhere (browser or Node), you have to provide the logic to select _which_ dictionary to use (as well as providing the dictionary contents, of course).

I provided some recipes here: https://github.com/lukeed/rosetta/issues/1#issuecomment-613840436

I'm not *correctly* watching this repo again. Please let me know if there's anything else I can help with 👍
